scret validation

diff --git a/.github/workflows/gce_deploy_staging_docker_compose.yml b/.github/workflows/gce_deploy_staging_docker_compose.yml
--- a/.github/workflows/gce_deploy_staging_docker_compose.yml
+++ b/.github/workflows/gce_deploy_staging_docker_compose.yml
@@ -57,7 +57,11 @@ jobs:
             )
 
         for name in "${secret_names[@]}"; do
-            echo $name
+            secret_name="secrets.${name}"
+            if [[ -z ${{ $secret_name }} ]]; then
+                echo "ERROR! Missing or empty secret [ $name ]!"
+                exit 1
+            fi
         done
 
 
