tes

diff --git a/.github/workflows/gce_deploy_staging_docker_compose.yml b/.github/workflows/gce_deploy_staging_docker_compose.yml
--- a/.github/workflows/gce_deploy_staging_docker_compose.yml
+++ b/.github/workflows/gce_deploy_staging_docker_compose.yml
@@ -58,7 +58,10 @@ jobs:
 
         for name in "${secret_names[@]}"; do
             secret_name="secrets.${name}"
-            echo ${{ $secret_name }}
+            if [[ -z ${{ secrets[$name] }} ]]; then
+                echo "ERROR! Missing or empty secret [ $name ]!"
+                exit 1
+            fi
         done
 
 
