test

diff --git a/.github/workflows/gce_deploy_staging_docker_compose.yml b/.github/workflows/gce_deploy_staging_docker_compose.yml
--- a/.github/workflows/gce_deploy_staging_docker_compose.yml
+++ b/.github/workflows/gce_deploy_staging_docker_compose.yml
@@ -59,10 +59,11 @@ jobs:
             )
 
         for name in "${secret_names[@]}"; do
-            if [[ -z ${{ secrets.$name }} ]]; then
-                echo "ERROR! Missing or empty secret [ $name ]!"
-                exit 1
-            fi
+            echo $name
+            # if [[ -z ${{ secrets.$name }} ]]; then
+            #     echo "ERROR! Missing or empty secret [ $name ]!"
+            #     exit 1
+            # fi
         done
 
 
